package nico.barklib;

import net.fabricmc.api.ModInitializer;
import net.minecraft.block.Blocks;
import net.minecraft.item.Items;
import net.minecraft.util.Identifier;
import nico.barklib.api.BarkWoodSet;
import nico.barklib.api.BarkWoodSetRegistry;

public class BarkLib implements ModInitializer {

    public static final String MOD_ID = "barklib";

    @Override
    public void onInitialize() {
        BarkWoodSetRegistry.registerWoodSets(
                BarkWoodSet.Factory.of(vanillaId("oak"))
                        .setPlanks(Blocks.OAK_PLANKS)
                        .setSlab(Blocks.OAK_SLAB)
                        .setStairs(Blocks.OAK_STAIRS)
                        .setFence(Blocks.OAK_FENCE, Blocks.OAK_FENCE_GATE)
                        .setDoor(Blocks.OAK_DOOR)
                        .setTrapdoor(Blocks.OAK_TRAPDOOR)
                        .setButton(Blocks.OAK_BUTTON)
                        .setPressurePlate(Blocks.OAK_PRESSURE_PLATE)
                        .setLog(Blocks.OAK_LOG, Blocks.STRIPPED_OAK_LOG)
                        .setWood(Blocks.OAK_WOOD, Blocks.STRIPPED_OAK_WOOD)
                        .setSign(Blocks.OAK_SIGN, Blocks.OAK_WALL_SIGN)
                        .setHangingSign(Blocks.OAK_HANGING_SIGN, Blocks.OAK_WALL_HANGING_SIGN)
                        .setBoat(Items.OAK_BOAT, Items.OAK_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("spruce"))
                        .setPlanks(Blocks.SPRUCE_PLANKS)
                        .setSlab(Blocks.SPRUCE_SLAB)
                        .setStairs(Blocks.SPRUCE_STAIRS)
                        .setFence(Blocks.SPRUCE_FENCE, Blocks.SPRUCE_FENCE_GATE)
                        .setDoor(Blocks.SPRUCE_DOOR)
                        .setTrapdoor(Blocks.SPRUCE_TRAPDOOR)
                        .setButton(Blocks.SPRUCE_BUTTON)
                        .setPressurePlate(Blocks.SPRUCE_PRESSURE_PLATE)
                        .setLog(Blocks.SPRUCE_LOG, Blocks.STRIPPED_SPRUCE_LOG)
                        .setWood(Blocks.SPRUCE_WOOD, Blocks.STRIPPED_SPRUCE_WOOD)
                        .setSign(Blocks.SPRUCE_SIGN, Blocks.SPRUCE_WALL_SIGN)
                        .setHangingSign(Blocks.SPRUCE_HANGING_SIGN, Blocks.SPRUCE_WALL_HANGING_SIGN)
                        .setBoat(Items.SPRUCE_BOAT, Items.SPRUCE_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("birch"))
                        .setPlanks(Blocks.BIRCH_PLANKS)
                        .setSlab(Blocks.BIRCH_SLAB)
                        .setStairs(Blocks.BIRCH_STAIRS)
                        .setFence(Blocks.BIRCH_FENCE, Blocks.BIRCH_FENCE_GATE)
                        .setDoor(Blocks.BIRCH_DOOR)
                        .setTrapdoor(Blocks.BIRCH_TRAPDOOR)
                        .setButton(Blocks.BIRCH_BUTTON)
                        .setPressurePlate(Blocks.BIRCH_PRESSURE_PLATE)
                        .setLog(Blocks.BIRCH_LOG, Blocks.STRIPPED_BIRCH_LOG)
                        .setWood(Blocks.BIRCH_WOOD, Blocks.STRIPPED_BIRCH_WOOD)
                        .setSign(Blocks.BIRCH_SIGN, Blocks.BIRCH_WALL_SIGN)
                        .setHangingSign(Blocks.BIRCH_HANGING_SIGN, Blocks.BIRCH_WALL_HANGING_SIGN)
                        .setBoat(Items.BIRCH_BOAT, Items.BIRCH_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("jungle"))
                        .setPlanks(Blocks.JUNGLE_PLANKS)
                        .setSlab(Blocks.JUNGLE_SLAB)
                        .setStairs(Blocks.JUNGLE_STAIRS)
                        .setFence(Blocks.JUNGLE_FENCE, Blocks.JUNGLE_FENCE_GATE)
                        .setDoor(Blocks.JUNGLE_DOOR)
                        .setTrapdoor(Blocks.JUNGLE_TRAPDOOR)
                        .setButton(Blocks.JUNGLE_BUTTON)
                        .setPressurePlate(Blocks.JUNGLE_PRESSURE_PLATE)
                        .setLog(Blocks.JUNGLE_LOG, Blocks.STRIPPED_JUNGLE_LOG)
                        .setWood(Blocks.JUNGLE_WOOD, Blocks.STRIPPED_JUNGLE_WOOD)
                        .setSign(Blocks.JUNGLE_SIGN, Blocks.JUNGLE_WALL_SIGN)
                        .setHangingSign(Blocks.JUNGLE_HANGING_SIGN, Blocks.JUNGLE_WALL_HANGING_SIGN)
                        .setBoat(Items.JUNGLE_BOAT, Items.JUNGLE_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("acacia"))
                        .setPlanks(Blocks.ACACIA_PLANKS)
                        .setSlab(Blocks.ACACIA_SLAB)
                        .setStairs(Blocks.ACACIA_STAIRS)
                        .setFence(Blocks.ACACIA_FENCE, Blocks.ACACIA_FENCE_GATE)
                        .setDoor(Blocks.ACACIA_DOOR)
                        .setTrapdoor(Blocks.ACACIA_TRAPDOOR)
                        .setButton(Blocks.ACACIA_BUTTON)
                        .setPressurePlate(Blocks.ACACIA_PRESSURE_PLATE)
                        .setLog(Blocks.ACACIA_LOG, Blocks.STRIPPED_ACACIA_LOG)
                        .setWood(Blocks.ACACIA_WOOD, Blocks.STRIPPED_ACACIA_WOOD)
                        .setSign(Blocks.ACACIA_SIGN, Blocks.ACACIA_WALL_SIGN)
                        .setHangingSign(Blocks.ACACIA_HANGING_SIGN, Blocks.ACACIA_WALL_HANGING_SIGN)
                        .setBoat(Items.ACACIA_BOAT, Items.ACACIA_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("dark_oak"))
                        .setPlanks(Blocks.DARK_OAK_PLANKS)
                        .setSlab(Blocks.DARK_OAK_SLAB)
                        .setStairs(Blocks.DARK_OAK_STAIRS)
                        .setFence(Blocks.DARK_OAK_FENCE, Blocks.DARK_OAK_FENCE_GATE)
                        .setDoor(Blocks.DARK_OAK_DOOR)
                        .setTrapdoor(Blocks.DARK_OAK_TRAPDOOR)
                        .setButton(Blocks.DARK_OAK_BUTTON)
                        .setPressurePlate(Blocks.DARK_OAK_PRESSURE_PLATE)
                        .setLog(Blocks.DARK_OAK_LOG, Blocks.STRIPPED_DARK_OAK_LOG)
                        .setWood(Blocks.DARK_OAK_WOOD, Blocks.STRIPPED_DARK_OAK_WOOD)
                        .setSign(Blocks.DARK_OAK_SIGN, Blocks.DARK_OAK_WALL_SIGN)
                        .setHangingSign(Blocks.DARK_OAK_HANGING_SIGN, Blocks.DARK_OAK_WALL_HANGING_SIGN)
                        .setBoat(Items.DARK_OAK_BOAT, Items.DARK_OAK_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("mangrove"))
                        .setPlanks(Blocks.MANGROVE_PLANKS)
                        .setSlab(Blocks.MANGROVE_SLAB)
                        .setStairs(Blocks.MANGROVE_STAIRS)
                        .setFence(Blocks.MANGROVE_FENCE, Blocks.MANGROVE_FENCE_GATE)
                        .setDoor(Blocks.MANGROVE_DOOR)
                        .setTrapdoor(Blocks.MANGROVE_TRAPDOOR)
                        .setButton(Blocks.MANGROVE_BUTTON)
                        .setPressurePlate(Blocks.MANGROVE_PRESSURE_PLATE)
                        .setLog(Blocks.MANGROVE_LOG, Blocks.STRIPPED_MANGROVE_LOG)
                        .setWood(Blocks.MANGROVE_WOOD, Blocks.STRIPPED_MANGROVE_WOOD)
                        .setSign(Blocks.MANGROVE_SIGN, Blocks.MANGROVE_WALL_SIGN)
                        .setHangingSign(Blocks.MANGROVE_HANGING_SIGN, Blocks.MANGROVE_WALL_HANGING_SIGN)
                        .setBoat(Items.MANGROVE_BOAT, Items.MANGROVE_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("cherry"))
                        .setPlanks(Blocks.CHERRY_PLANKS)
                        .setSlab(Blocks.CHERRY_SLAB)
                        .setStairs(Blocks.CHERRY_STAIRS)
                        .setFence(Blocks.CHERRY_FENCE, Blocks.CHERRY_FENCE_GATE)
                        .setDoor(Blocks.CHERRY_DOOR)
                        .setTrapdoor(Blocks.CHERRY_TRAPDOOR)
                        .setButton(Blocks.CHERRY_BUTTON)
                        .setPressurePlate(Blocks.CHERRY_PRESSURE_PLATE)
                        .setLog(Blocks.CHERRY_LOG, Blocks.STRIPPED_CHERRY_LOG)
                        .setWood(Blocks.CHERRY_WOOD, Blocks.STRIPPED_CHERRY_WOOD)
                        .setSign(Blocks.CHERRY_SIGN, Blocks.CHERRY_WALL_SIGN)
                        .setHangingSign(Blocks.CHERRY_HANGING_SIGN, Blocks.CHERRY_WALL_HANGING_SIGN)
                        .setBoat(Items.CHERRY_BOAT, Items.CHERRY_CHEST_BOAT)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("bamboo"))
                        .setPlanks(Blocks.BAMBOO_PLANKS)
                        .setSlab(Blocks.BAMBOO_SLAB)
                        .setStairs(Blocks.BAMBOO_STAIRS)
                        .setFence(Blocks.BAMBOO_FENCE, Blocks.BAMBOO_FENCE_GATE)
                        .setDoor(Blocks.BAMBOO_DOOR)
                        .setTrapdoor(Blocks.BAMBOO_TRAPDOOR)
                        .setButton(Blocks.BAMBOO_BUTTON)
                        .setPressurePlate(Blocks.BAMBOO_PRESSURE_PLATE)
                        .setLog(Blocks.BAMBOO_BLOCK, Blocks.STRIPPED_BAMBOO_BLOCK)
                        .setSign(Blocks.BAMBOO_SIGN, Blocks.BAMBOO_WALL_SIGN)
                        .setHangingSign(Blocks.BAMBOO_HANGING_SIGN, Blocks.BAMBOO_WALL_HANGING_SIGN)
                        .setBoat(Items.BAMBOO_RAFT, Items.BAMBOO_CHEST_RAFT)
                        .set(vanillaId("mosaic"), Blocks.BAMBOO_MOSAIC)
                        .set(vanillaId("mosaic_slab"), Blocks.BAMBOO_MOSAIC_SLAB)
                        .set(vanillaId("mosaic_stairs"), Blocks.BAMBOO_MOSAIC_STAIRS)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("crimson"))
                        .setPlanks(Blocks.CRIMSON_PLANKS)
                        .setSlab(Blocks.CRIMSON_SLAB)
                        .setStairs(Blocks.CRIMSON_STAIRS)
                        .setFence(Blocks.CRIMSON_FENCE, Blocks.CRIMSON_FENCE_GATE)
                        .setDoor(Blocks.CRIMSON_DOOR)
                        .setTrapdoor(Blocks.CRIMSON_TRAPDOOR)
                        .setButton(Blocks.CRIMSON_BUTTON)
                        .setPressurePlate(Blocks.CRIMSON_PRESSURE_PLATE)
                        .setLog(Blocks.CRIMSON_STEM, Blocks.STRIPPED_CRIMSON_STEM)
                        .setWood(Blocks.CRIMSON_HYPHAE, Blocks.STRIPPED_CRIMSON_HYPHAE)
                        .setSign(Blocks.CRIMSON_SIGN, Blocks.CRIMSON_WALL_SIGN)
                        .setHangingSign(Blocks.CRIMSON_HANGING_SIGN, Blocks.CRIMSON_WALL_HANGING_SIGN)
                        .build(),
                BarkWoodSet.Factory.of(vanillaId("warped"))
                        .setPlanks(Blocks.WARPED_PLANKS)
                        .setSlab(Blocks.WARPED_SLAB)
                        .setStairs(Blocks.WARPED_STAIRS)
                        .setFence(Blocks.WARPED_FENCE, Blocks.WARPED_FENCE_GATE)
                        .setDoor(Blocks.WARPED_DOOR)
                        .setTrapdoor(Blocks.WARPED_TRAPDOOR)
                        .setButton(Blocks.WARPED_BUTTON)
                        .setPressurePlate(Blocks.WARPED_PRESSURE_PLATE)
                        .setLog(Blocks.WARPED_STEM, Blocks.STRIPPED_WARPED_STEM)
                        .setWood(Blocks.WARPED_HYPHAE, Blocks.STRIPPED_WARPED_HYPHAE)
                        .setSign(Blocks.WARPED_SIGN, Blocks.WARPED_WALL_SIGN)
                        .setHangingSign(Blocks.WARPED_HANGING_SIGN, Blocks.WARPED_WALL_HANGING_SIGN)
                        .build()
        );
    }

    private static Identifier vanillaId(String name) {
        return Identifier.of(Identifier.DEFAULT_NAMESPACE, name);
    }

    public static Identifier id(String name) {
        return Identifier.of(MOD_ID, name);
    }
}